sonar.projectKey=KegelNetzwerk_kegelnetzwerk-app
sonar.organization=kegelnetzwerk

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sources=src,app
sonar.exclusions=**/node_modules/**,**/.expo/**,**/android/**,**/ios/**
sonar.coverage.exclusions=app/**
